# Generated by Django 5.0.6 on 2024-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_name',
            field=models.CharField(default='Unnamed Contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='editing_options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='equipment',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='event_duration',
            field=models.CharField(default='1 hour', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='operator_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='operator_duration_unit',
            field=models.CharField(default='hour', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='other_equipment',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='job',
            name='postcode',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='service',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
