# Generated by Django 5.0.6 on 2024-05-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_contact_email_alter_job_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
    ]
