# Generated by Django 5.0.6 on 2024-06-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='event_duration',
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_phone',
            field=models.CharField(default='0000-000-0000', max_length=15),
        ),
    ]
